# [56]  # BSC
# rpc = "https://my-custom-rpc.com/my-api-key"
# batch_request_size = 500
# max_fee_per_gas = 1.1  # gwei

# [185]  # Mintchain
# proxy = "ip:port:user:password" # any format

[5]  # Goerli
rpc = "https://eth-goerli.public.blastapi.io"

[10]
rpc = "https://rpc.ankr.com/optimism"
batch_request_size = 10