# Настройка сетей
# Доступные параметры:
# rpc - кастомный rpc
# batch_request_size
# max_fee_per_gas
#
# Например:
# [56]  # BSC
# rpc = "https://my-custom-rpc.com/my-api-key"
# batch_request_size = 500
# max_fee_per_gas = 1.1  # gwei
